# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'fede2WSL'

steps:
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'newConnection'
    cliInstallationRepo: 'jfrogcli'
- task: Docker@2
  inputs:
    containerRegistry: 'fedeRegistry'
    repository: 'prova2'
    command: 'Build'
    Dockerfile: '**/Dockerfile'


- task: Docker@2
  inputs:
    containerRegistry: 'fedeRegistry'
    repository: 'prova2'
    command: 'Push'
    Dockerfile: '**/Dockerfile'
    tags: '279' # mi chiamo una gia esistente