trigger:
  branches:
    include:
      - main

pool:
  name: fede2WSL

steps:
  - task: ArtifactoryToolsInstaller@1
    inputs:
      artifactoryService: 'newConnection'
      cliInstallationRepo: 'jfrogcli'

  - task: Docker@2
    inputs:
      containerRegistry: 'fedeRegistry'
      repository: 'prova2'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildNumber)'
      buildContext: '$(Build.SourcesDirectory)'

  - script: |
      apt-get update && apt-get install -yq curl
      response=$(curl -I -u fede:';'+i5}SAf^+x3F';*' -s -o /dev/null -w "%{http_code}" https://diocane.jfrog.io/artifactory/prova2/)
      if [ $response -eq 200 ]; then
        echo "Artifactory connection successful"
      else
        echo "Artifactory connection failed"
        exit 1
      fi
    displayName: 'Check Artifactory Connection'

  - task: ArtifactoryDocker@2
    displayName: 'Push Docker Image to Artifactory'
    inputs:
      command: 'push'
      imageName: 'prova2'
      targetRepo: 'prova2'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      artifactoryService: 'newConnection'

