trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'fedeRegistry'
      repository: 'prova2'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildNumber)'
      buildContext: '$(Build.SourcesDirectory)'

  - script: |
      curl -u fede:';+i5}SAf^+x3F;*' -I https://diocane.jfrog.io/artifactory/prova2/
    displayName: 'Check Artifactory Connection'
