trigger:
  branches:
    include:
      - main

pool:
  name: fede2WSL

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'fedeRegistry'
      repository: 'prova2/nginx'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildNumber)'
      buildContext: '$(Build.SourcesDirectory)'

  - task: ArtifactoryDocker@1
    displayName: 'Push Docker Image to Artifactory'
    inputs:
      command: 'push'
      imageName: 'diocane.jfrog.io/prova2/nginx:$(Build.BuildNumber)'
      targetRepo: 'prova2/nginx'
      artifactoryService: 'newConnection'

