trigger:
- main

pool: 'fede2WSL'

steps:
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'newConnection'
    cliInstallationRepo: 'jfrogcli'
- task: Docker@2
  inputs:
    containerRegistry: 'fedeRegistry'
    repository: 'prova2'
    command: 'Build'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildNumber)'

- task: Docker@2
  inputs:
    containerRegistry: 'fedeRegistry'
    repository: 'prova2'
    command: 'Push'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildNumber)'
    context: '$(Build.ArtifactStagingDirectory)' 