trigger:
  branches:
    include:
      - main

variables:
  buildIdName: 'last'
  Build.BuildId: 'latest'

pool:
  name: fede2WSL

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'fedeRegistry'
      repository: 'prova2/nginx'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: '$(buildIdName)-$(Build.BuildId)'

  - task: ArtifactoryDocker@1
    displayName: 'Push Docker Image to Artifactory'
    inputs:
      command: 'push'
      imageName: 'diobestia.jfrog.io/prova2/nginx:$(buildIdName)-$(Build.BuildId)'
      targetRepo: 'prova2/nginx'
      artifactoryService: 'newConnection'
