trigger:
  branches:
    include:
      - main

variables:
  imageName: 'prova2/nginx:latest'

pool:
  name: fede2WSL

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'fedeRegistry'
      repository: 'prova2/nginx'
      command: 'build'
      Dockerfile: '**/Dockerfile'



  - task: ArtifactoryDocker@1
    displayName: 'Push Docker Image to Artifactory'
    inputs:
      command: 'push'
      imageName: 'diobestia.jfrog.io/$(imageName)'
      targetRepo: 'prova2/nginx'
      artifactoryService: 'newConnection'

